# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dawid/c++/CPPWA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dawid/c++/CPPWA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawid/c++/CPPWA/CMakeFiles /home/dawid/c++/CPPWA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawid/c++/CPPWA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CPPWA

# Build rule for target.
CPPWA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CPPWA
.PHONY : CPPWA

# fast build rule for target.
CPPWA/fast:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/build
.PHONY : CPPWA/fast

src/HTTPHeader/HTTPHeader.o: src/HTTPHeader/HTTPHeader.cpp.o

.PHONY : src/HTTPHeader/HTTPHeader.o

# target to build an object file
src/HTTPHeader/HTTPHeader.cpp.o:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/HTTPHeader/HTTPHeader.cpp.o
.PHONY : src/HTTPHeader/HTTPHeader.cpp.o

src/HTTPHeader/HTTPHeader.i: src/HTTPHeader/HTTPHeader.cpp.i

.PHONY : src/HTTPHeader/HTTPHeader.i

# target to preprocess a source file
src/HTTPHeader/HTTPHeader.cpp.i:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/HTTPHeader/HTTPHeader.cpp.i
.PHONY : src/HTTPHeader/HTTPHeader.cpp.i

src/HTTPHeader/HTTPHeader.s: src/HTTPHeader/HTTPHeader.cpp.s

.PHONY : src/HTTPHeader/HTTPHeader.s

# target to generate assembly for a file
src/HTTPHeader/HTTPHeader.cpp.s:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/HTTPHeader/HTTPHeader.cpp.s
.PHONY : src/HTTPHeader/HTTPHeader.cpp.s

src/config/Config.o: src/config/Config.cpp.o

.PHONY : src/config/Config.o

# target to build an object file
src/config/Config.cpp.o:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/config/Config.cpp.o
.PHONY : src/config/Config.cpp.o

src/config/Config.i: src/config/Config.cpp.i

.PHONY : src/config/Config.i

# target to preprocess a source file
src/config/Config.cpp.i:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/config/Config.cpp.i
.PHONY : src/config/Config.cpp.i

src/config/Config.s: src/config/Config.cpp.s

.PHONY : src/config/Config.s

# target to generate assembly for a file
src/config/Config.cpp.s:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/config/Config.cpp.s
.PHONY : src/config/Config.cpp.s

src/database/Database.o: src/database/Database.cpp.o

.PHONY : src/database/Database.o

# target to build an object file
src/database/Database.cpp.o:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/Database.cpp.o
.PHONY : src/database/Database.cpp.o

src/database/Database.i: src/database/Database.cpp.i

.PHONY : src/database/Database.i

# target to preprocess a source file
src/database/Database.cpp.i:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/Database.cpp.i
.PHONY : src/database/Database.cpp.i

src/database/Database.s: src/database/Database.cpp.s

.PHONY : src/database/Database.s

# target to generate assembly for a file
src/database/Database.cpp.s:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/Database.cpp.s
.PHONY : src/database/Database.cpp.s

src/database/repositories/RepositoryFactory.o: src/database/repositories/RepositoryFactory.cpp.o

.PHONY : src/database/repositories/RepositoryFactory.o

# target to build an object file
src/database/repositories/RepositoryFactory.cpp.o:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/RepositoryFactory.cpp.o
.PHONY : src/database/repositories/RepositoryFactory.cpp.o

src/database/repositories/RepositoryFactory.i: src/database/repositories/RepositoryFactory.cpp.i

.PHONY : src/database/repositories/RepositoryFactory.i

# target to preprocess a source file
src/database/repositories/RepositoryFactory.cpp.i:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/RepositoryFactory.cpp.i
.PHONY : src/database/repositories/RepositoryFactory.cpp.i

src/database/repositories/RepositoryFactory.s: src/database/repositories/RepositoryFactory.cpp.s

.PHONY : src/database/repositories/RepositoryFactory.s

# target to generate assembly for a file
src/database/repositories/RepositoryFactory.cpp.s:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/RepositoryFactory.cpp.s
.PHONY : src/database/repositories/RepositoryFactory.cpp.s

src/database/repositories/UserRepository.o: src/database/repositories/UserRepository.cpp.o

.PHONY : src/database/repositories/UserRepository.o

# target to build an object file
src/database/repositories/UserRepository.cpp.o:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/UserRepository.cpp.o
.PHONY : src/database/repositories/UserRepository.cpp.o

src/database/repositories/UserRepository.i: src/database/repositories/UserRepository.cpp.i

.PHONY : src/database/repositories/UserRepository.i

# target to preprocess a source file
src/database/repositories/UserRepository.cpp.i:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/UserRepository.cpp.i
.PHONY : src/database/repositories/UserRepository.cpp.i

src/database/repositories/UserRepository.s: src/database/repositories/UserRepository.cpp.s

.PHONY : src/database/repositories/UserRepository.s

# target to generate assembly for a file
src/database/repositories/UserRepository.cpp.s:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/UserRepository.cpp.s
.PHONY : src/database/repositories/UserRepository.cpp.s

src/database/repositories/mysql/MysqlRepositoryFactory.o: src/database/repositories/mysql/MysqlRepositoryFactory.cpp.o

.PHONY : src/database/repositories/mysql/MysqlRepositoryFactory.o

# target to build an object file
src/database/repositories/mysql/MysqlRepositoryFactory.cpp.o:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/mysql/MysqlRepositoryFactory.cpp.o
.PHONY : src/database/repositories/mysql/MysqlRepositoryFactory.cpp.o

src/database/repositories/mysql/MysqlRepositoryFactory.i: src/database/repositories/mysql/MysqlRepositoryFactory.cpp.i

.PHONY : src/database/repositories/mysql/MysqlRepositoryFactory.i

# target to preprocess a source file
src/database/repositories/mysql/MysqlRepositoryFactory.cpp.i:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/mysql/MysqlRepositoryFactory.cpp.i
.PHONY : src/database/repositories/mysql/MysqlRepositoryFactory.cpp.i

src/database/repositories/mysql/MysqlRepositoryFactory.s: src/database/repositories/mysql/MysqlRepositoryFactory.cpp.s

.PHONY : src/database/repositories/mysql/MysqlRepositoryFactory.s

# target to generate assembly for a file
src/database/repositories/mysql/MysqlRepositoryFactory.cpp.s:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/mysql/MysqlRepositoryFactory.cpp.s
.PHONY : src/database/repositories/mysql/MysqlRepositoryFactory.cpp.s

src/database/repositories/mysql/MysqlUserRepository.o: src/database/repositories/mysql/MysqlUserRepository.cpp.o

.PHONY : src/database/repositories/mysql/MysqlUserRepository.o

# target to build an object file
src/database/repositories/mysql/MysqlUserRepository.cpp.o:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/mysql/MysqlUserRepository.cpp.o
.PHONY : src/database/repositories/mysql/MysqlUserRepository.cpp.o

src/database/repositories/mysql/MysqlUserRepository.i: src/database/repositories/mysql/MysqlUserRepository.cpp.i

.PHONY : src/database/repositories/mysql/MysqlUserRepository.i

# target to preprocess a source file
src/database/repositories/mysql/MysqlUserRepository.cpp.i:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/mysql/MysqlUserRepository.cpp.i
.PHONY : src/database/repositories/mysql/MysqlUserRepository.cpp.i

src/database/repositories/mysql/MysqlUserRepository.s: src/database/repositories/mysql/MysqlUserRepository.cpp.s

.PHONY : src/database/repositories/mysql/MysqlUserRepository.s

# target to generate assembly for a file
src/database/repositories/mysql/MysqlUserRepository.cpp.s:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/mysql/MysqlUserRepository.cpp.s
.PHONY : src/database/repositories/mysql/MysqlUserRepository.cpp.s

src/database/repositories/test/TestRepositoryFactory.o: src/database/repositories/test/TestRepositoryFactory.cpp.o

.PHONY : src/database/repositories/test/TestRepositoryFactory.o

# target to build an object file
src/database/repositories/test/TestRepositoryFactory.cpp.o:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/test/TestRepositoryFactory.cpp.o
.PHONY : src/database/repositories/test/TestRepositoryFactory.cpp.o

src/database/repositories/test/TestRepositoryFactory.i: src/database/repositories/test/TestRepositoryFactory.cpp.i

.PHONY : src/database/repositories/test/TestRepositoryFactory.i

# target to preprocess a source file
src/database/repositories/test/TestRepositoryFactory.cpp.i:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/test/TestRepositoryFactory.cpp.i
.PHONY : src/database/repositories/test/TestRepositoryFactory.cpp.i

src/database/repositories/test/TestRepositoryFactory.s: src/database/repositories/test/TestRepositoryFactory.cpp.s

.PHONY : src/database/repositories/test/TestRepositoryFactory.s

# target to generate assembly for a file
src/database/repositories/test/TestRepositoryFactory.cpp.s:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/test/TestRepositoryFactory.cpp.s
.PHONY : src/database/repositories/test/TestRepositoryFactory.cpp.s

src/database/repositories/test/TestUserRepository.o: src/database/repositories/test/TestUserRepository.cpp.o

.PHONY : src/database/repositories/test/TestUserRepository.o

# target to build an object file
src/database/repositories/test/TestUserRepository.cpp.o:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/test/TestUserRepository.cpp.o
.PHONY : src/database/repositories/test/TestUserRepository.cpp.o

src/database/repositories/test/TestUserRepository.i: src/database/repositories/test/TestUserRepository.cpp.i

.PHONY : src/database/repositories/test/TestUserRepository.i

# target to preprocess a source file
src/database/repositories/test/TestUserRepository.cpp.i:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/test/TestUserRepository.cpp.i
.PHONY : src/database/repositories/test/TestUserRepository.cpp.i

src/database/repositories/test/TestUserRepository.s: src/database/repositories/test/TestUserRepository.cpp.s

.PHONY : src/database/repositories/test/TestUserRepository.s

# target to generate assembly for a file
src/database/repositories/test/TestUserRepository.cpp.s:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/database/repositories/test/TestUserRepository.cpp.s
.PHONY : src/database/repositories/test/TestUserRepository.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CPPWA.dir/build.make CMakeFiles/CPPWA.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... CPPWA"
	@echo "... edit_cache"
	@echo "... src/HTTPHeader/HTTPHeader.o"
	@echo "... src/HTTPHeader/HTTPHeader.i"
	@echo "... src/HTTPHeader/HTTPHeader.s"
	@echo "... src/config/Config.o"
	@echo "... src/config/Config.i"
	@echo "... src/config/Config.s"
	@echo "... src/database/Database.o"
	@echo "... src/database/Database.i"
	@echo "... src/database/Database.s"
	@echo "... src/database/repositories/RepositoryFactory.o"
	@echo "... src/database/repositories/RepositoryFactory.i"
	@echo "... src/database/repositories/RepositoryFactory.s"
	@echo "... src/database/repositories/UserRepository.o"
	@echo "... src/database/repositories/UserRepository.i"
	@echo "... src/database/repositories/UserRepository.s"
	@echo "... src/database/repositories/mysql/MysqlRepositoryFactory.o"
	@echo "... src/database/repositories/mysql/MysqlRepositoryFactory.i"
	@echo "... src/database/repositories/mysql/MysqlRepositoryFactory.s"
	@echo "... src/database/repositories/mysql/MysqlUserRepository.o"
	@echo "... src/database/repositories/mysql/MysqlUserRepository.i"
	@echo "... src/database/repositories/mysql/MysqlUserRepository.s"
	@echo "... src/database/repositories/test/TestRepositoryFactory.o"
	@echo "... src/database/repositories/test/TestRepositoryFactory.i"
	@echo "... src/database/repositories/test/TestRepositoryFactory.s"
	@echo "... src/database/repositories/test/TestUserRepository.o"
	@echo "... src/database/repositories/test/TestUserRepository.i"
	@echo "... src/database/repositories/test/TestUserRepository.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

